# Generated by Django 6.0.2 on 2026-04-13 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("defects", "0002_product_expiry_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="defect",
            name="version",
        ),
    ]
